### ISSUE TITLE
Trying to catch obscure math domain error that occurs in the context of large scale multidimensional parameter searches.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#17]
Hi @rgerkin and @scrook

I have decided to address this issue as aggressively as possible, as it has been stopping progress, as longer parameter searches evaluations only finish intermittently without experiencing the error.

My understanding of the origin of the error has changed. I no longer believe math domain error is eminating from scidash: neuronunit and or sciunit. I believe it is a scoop error, and (speculating now) I believe it could be something relating to memory buffers for the transport of messages between the broker and the worker CPUs.

Also the problem does not occur at the same point, in every search, even though the grid_search/exhaustive search contains no stochastic processes or PRNGs. I believe however that there is a reason why the error occurs or fails to occur in a launch specific way is because whenever I invoke python with scoop, the CPUs responsible for managing specific cell models are different, depending on the state of the computer when I launch parallel python. Therefore the CPUs responsible for transporting and receiving specific cell models, and the communication pattern between CPUs is different on different launches of the program.

I have noticed that you can launch python scoop with a verbose flag (```python -m scoop --v file_name.py```), and I also have started to try to debug the scoop code itself. I took a long time to suspect scoop itself as use of scoop results in hiding stderr, since the worker CPU that experiences the error quits and sends a SIGPOLL error message to the broker. Only the SIGPOLL error message reaches the users stderr (as probably it is only broker CPU which can write to stderr), with the consequence that developer never sees the original error message. I am hoping that use of the verbose flag will change this. 

I had become accustomed to overlooking scoops actual stderr for this reason however, since the error message it gives, is usually uninformative about the real source of the problem, but I believe this habit has lead to the me misreading the real source of the error. As I wrote above the error type is a math domain error.

The stderr from scoop is on line 55 of `/home/jovyan/scoop/scoop/_control.py` which reads:  ```self._sum -= math.log(self[-1]) ```

Meanwhile I had adjusted both files exhaustive_search.py and nsga.py such that models that fire a rheobase spike at I<=0pA current injection are discarded, meaning that sciunit should not be exposed to tests, where it needs to use math.log on a negative float argument. Therefore I believe its reasonable to believe that the error is in scoop.

I believe that line 55 of : scoop/scoop/_control.py is calculating log of an argument because its trying to distribute that TCP/IP packets associated with evaluating an iterator, in a load balanced way, and for some reason calculating log(x) of either the function, or the iterators associated data, helps scoop achieve load_balanced distributed function mapping.

My intuition is that scoop does not have robust protection against buffer over flow, and that the function I have given it to evaluate is just too big for the broker to transmit to workers, or something like that. Anyway, from here, I can try to message the scoop user group (a user and developer community), I can try to debug `scoop/scoop/_control.py` myself, and I can try to see if I can  try to change the code to prevent `math.log(x)` at line 55 of `scoop/scoop/_control.py` from evaluating negative, or nan values by adding an exception and exception handling clause. 

```
    def appendleft(self, x):
        try:
            ln_x = math.log(x)
        except ValueError:
            # Make it smaller than possible clock precision                                                                                                                                                                                   
            ln_x = 1e-100
        if len(self) >= self.maxlen:
            self._sum -= math.log(self[-1])      ##This is line 55
            self._squared_sum -= math.log(self[-1]) ** 2
        self._sum += ln_x
        self._squared_sum += ln_x ** 2
        super(_stat, self).appendleft(x)

```

I will use the output below, to try to infer the parameter subset that results in this `sciunit` error.
```
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 42 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 31.111111111111111, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 current and got 47 spikes on model {'b': -3.6666666666666668e-09, 'vr': -58.333333333333336, 'a': 0.105, 'vpeak': 32.222222222222221}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 current and got 47 spikes on model {'a': 0.105, 'vpeak': 33.333333333333336, 'b': -3.6666666666666668e-09, 'vr': -58.333333333333336}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 pA current and got 40 spikes on model {'a': 0.105, 'vr': -63.888888888888886, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 42 spikes on model {'vr': -58.333333333333336, 'vpeak': 34.444444444444443, 'a': 0.105, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 42 spikes on model {'vr': -58.333333333333336, 'vpeak': 35.555555555555557, 'b': -3.6666666666666668e-09, 'a': 0.105}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 42 spikes on model {'b': -3.6666666666666668e-09, 'vr': -58.333333333333336, 'a': 0.105, 'vpeak': 37.777777777777779}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 42 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 206.37860082304542 current and got 51 spikes on model {'b': -3.6666666666666668e-09, 'vpeak': 36.666666666666664, 'vr': -58.333333333333336, 'a': 0.105}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 current and got 48 spikes on model {'b': -3.6666666666666668e-09, 'vr': -55.555555555555557, 'a': 0.105, 'vpeak': 30.0}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 current and got 48 spikes on model {'a': 0.105, 'vpeak': 31.111111111111111, 'b': -3.6666666666666668e-09, 'vr': -55.555555555555557}
8 CPUs are testing different values of current injections simultaneously Injected 94.59019204389585 current and got 22 spikes on model {'a': 0.105, 'vr': -55.555555555555557, 'vpeak': 32.222222222222221, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 44 spikes on model {'vr': -55.555555555555557, 'vpeak': 33.333333333333336, 'a': 0.105, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 44 spikes on model {'vr': -55.555555555555557, 'vpeak': 34.444444444444443, 'b': -3.6666666666666668e-09, 'a': 0.105}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 44 spikes on model {'b': -3.6666666666666668e-09, 'vr': -55.555555555555557, 'a': 0.105, 'vpeak': 35.555555555555557}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 298, in <module>
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 92, in main
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 285, in run
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 266, in futures_startup
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 65, in _startup
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 281, in runController
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_types.py", line 132, in _switch
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 164, in runFuture
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 55, in appendleft
ValueError: math domain error
8 CPUs are testing different values of current injections simultaneously Injected -346.8307041609514 pA current and got 0 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 206.37860082304542 current and got 52 spikes on model {'b': -3.6666666666666668e-09, 'vpeak': 37.777777777777779, 'vr': -55.555555555555557, 'a': 0.105}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 current and got 48 spikes on model {'a': 0.105, 'vpeak': 40.0, 'b': -3.6666666666666668e-09, 'vr': -55.555555555555557}
8 CPUs are testing different values of current injections simultaneously Injected 189.1803840877917 current and got 48 spikes on model {'b': -3.6666666666666668e-09, 'vr': -55.555555555555557, 'a': 0.105, 'vpeak': 38.888888888888886}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 46 spikes on model {'vr': -52.777777777777779, 'vpeak': 31.111111111111111, 'a': 0.105, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 94.59019204389585 current and got 26 spikes on model {'a': 0.105, 'vr': -52.777777777777779, 'vpeak': 30.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 173.4153520804757 current and got 46 spikes on model {'vr': -52.777777777777779, 'vpeak': 32.222222222222221, 'b': -3.6666666666666668e-09, 'a': 0.105}
8 CPUs are testing different values of current injections simultaneously Injected -260.12302812071357 pA current and got 0 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected -173.4153520804757 pA current and got 0 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected -86.70767604023786 pA current and got 0 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 0.0 pA current and got 0 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
8 CPUs are testing different values of current injections simultaneously Injected 86.70767604023786 pA current and got 15 spikes on model {'a': 0.105, 'vr': -58.333333333333336, 'vpeak': 40.0, 'b': -3.6666666666666668e-09}
```

**Comment by rgerkin** [comment]
@russelljjarvis 
One way around not getting stderr printed out is just to log things to a file.  I think there is a logger module in python that makes this pretty easy.  You just have to add explicit logging commands.  I don't know if this would help in your situation.  

The root problem sounds pretty difficult.  What does self[-1] refer to?  Is it a value computed by NeuronUnit, or received from the data?  Or is it something that scoop uses that has nothing to do with the problem?

**Comment by russelljjarvis** [comment]
I no longer believe this is a problem.
