### ISSUE TITLE
parallel deap scoop

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#2]
scoop fails to use futures.map because the function that futures.map is supposed to evaluate is not pickable (see below):

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 150, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/opt/conda/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Optimize.py", line 170, in <module>
    pop = my_test.optimize(model,rov,param)
  File "Optimize.py", line 145, in optimize
    NDIM=3,OBJ_SIZE=6,seed_in=1)
  File "/home/mnt/neuronunit/software_tests/../../neuronunit/deapcontainer/deap_container.py", line 173, in sciunit_optimize_nsga
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/fallbacks.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 129, in map
    futures = _mapFuture(func, *iterables)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 94, in _mapFuture
    childrenList.append(submit(callable_, *args))
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/fallbacks.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 304, in submit
    control.execQueue.append(child)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_types.py", line 309, in append
    self.socket.sendFuture(sending_future)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_comm/scoopzmq.py", line 369, in sendFuture
    pickle.dumps(future, pickle.HIGHEST_PROTOCOL),
AttributeError: Can't pickle local object 'DeapContainer.sciunit_optimize_nsga.<locals>.callsciunitjudge'
```

I have isolated the problem with scoop to attempting to pickle a NEURON object.

```
        with open('filename.pickle', 'wb') as handle:
            pickle.dump(self.model,handle)
```
when self.model contains a NEURON object.
```
TypeError: HocObject: Only Vector instance can be pickled
```

**Comment by russelljjarvis** [comment]
![evolved_pop](https://cloud.githubusercontent.com/assets/7786645/21972979/98f589ea-db7a-11e6-8125-bf8ea0b75a80.png)
![initial_pop](https://cloud.githubusercontent.com/assets/7786645/21972977/98f3e98c-db7a-11e6-9923-1b3a3396775b.png)
![snap_shot_at1](https://cloud.githubusercontent.com/assets/7786645/21972980/98f5858a-db7a-11e6-89db-ccd6a86e510c.png)
![snap_shot_at2](https://cloud.githubusercontent.com/assets/7786645/21972978/98f53058-db7a-11e6-8433-8825136797d0.png)
![snap_shot_at3](https://cloud.githubusercontent.com/assets/7786645/21972981/98f73ccc-db7a-11e6-99b4-45dc376d3cbd.png)
![snap_shot_at4](https://cloud.githubusercontent.com/assets/7786645/21972982/98f87416-db7a-11e6-80cf-78e8af81cd41.png)
![snap_shot_at5](https://cloud.githubusercontent.com/assets/7786645/21972983/9909953e-db7a-11e6-8239-11b77ecb1d61.png)

Hi @rgerkin 
These are some figures that are output from the multiobjective parallel deap scoop algorithm.
It can be launched by executing 
`python -m scoop nsga3.py`
From the dev branch and the directory software_tests as can be found [here](https://github.com/russelljjarvis/neuronunit/tree/dev/neuronunit/software_tests/nsga3.py)

**Comment by russelljjarvis** [comment]
However the [travis]( https://travis-ci.org/scidash/neuronunit) build is failing because of the way I am indexing score_matrix.sort_keys().
Since travis is building the whole scidash docker stacks from scratch. This suggests something must have changed recently in sciunit.

**Comment by rgerkin** [comment]
@russelljjarvis 
Where do you stand on this issue?  Travis seems to be passing now.

**Comment by russelljjarvis** [comment]
Sorry I did not see this. Yes this issue is now closed. The travis builds do not necessarily reflect that well about whats happening on my local machine, unless I deem important that it does reflect well.
