### ISSUE TITLE
broken aibs.py file/ Allen Brain API changes etc.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#8]
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: '354190013_rheobase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 298, in <module>
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 92, in main
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 252, in run
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 213, in setupEnvironment
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 35, in <lambda>
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "exhaustive_search.py", line 19, in <module>
    import get_neab
  File "/home/jovyan/neuronunit/neuronunit/tests/get_neab.py", line 31, in <module>
    observation = aibs.get_observation(dataset_id,'rheobase')
  File "/home/jovyan/neuronunit/neuronunit/tests/../../neuronunit/aibs.py", line 27, in get_observation
    value = db[identifier]
  File "/opt/conda/lib/python3.5/shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
EOFError: Ran out of input
[2017-02-28 23:09:08,293] launcher  (127.0.0.1:45736) INFO    Root process is done.
[2017-02-28 23:09:08,339] launcher  (127.0.0.1:45736) INFO    Finished cleaning spawned subprocesses.
```

**Comment by rgerkin** [comment]
This hasn't been a problem for quite a while.
